# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-24 02:06
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('industry', '0001_initial'),
        ('customertype', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('creditterm', '0001_initial'),
        ('currency', '0001_initial'),
        ('bankaccount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('address1', models.CharField(max_length=250)),
                ('address2', models.CharField(blank=True, max_length=250, null=True)),
                ('address3', models.CharField(blank=True, max_length=250, null=True)),
                ('telno1', models.CharField(max_length=20)),
                ('telno2', models.CharField(blank=True, max_length=20, null=True)),
                ('telno3', models.CharField(blank=True, max_length=20, null=True)),
                ('faxno1', models.CharField(blank=True, max_length=20, null=True)),
                ('faxno2', models.CharField(blank=True, max_length=20, null=True)),
                ('tin', models.CharField(blank=True, max_length=15, null=True)),
                ('pagerno', models.CharField(blank=True, max_length=20, null=True)),
                ('payterms', models.CharField(max_length=20)),
                ('creditlimit', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('creditstatus', models.CharField(blank=True, choices=[('Y', 'Yes'), ('B', 'Bad'), ('A', 'Auto-CF')], max_length=1, null=True)),
                ('creditrating', models.CharField(blank=True, max_length=5, null=True)),
                ('contactperson', models.CharField(blank=True, max_length=250, null=True)),
                ('contactposition', models.CharField(blank=True, max_length=250, null=True)),
                ('contactemail', models.CharField(blank=True, max_length=250, null=True)),
                ('remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('multiplestatus', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, null=True)),
                ('beg_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('beg_code', models.CharField(blank=True, choices=[('D', 'Debit'), ('C', 'Credit')], max_length=1, null=True)),
                ('beg_date', models.DateField(blank=True, null=True)),
                ('end_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('end_code', models.CharField(blank=True, choices=[('D', 'Debit'), ('C', 'Credit')], max_length=1, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('C', 'Cancelled'), ('O', 'Posted'), ('P', 'Printed')], default='A', max_length=1)),
                ('enterdate', models.DateTimeField(auto_now_add=True)),
                ('modifydate', models.DateTimeField(default=datetime.datetime(2017, 1, 24, 10, 6, 25, 543626))),
                ('isdeleted', models.IntegerField(default=0)),
                ('bankaccount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bankaccount_id', to='bankaccount.Bankaccount')),
                ('creditterm', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='creditterm_id', to='creditterm.Creditterm')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_currency_id', to='currency.Currency')),
                ('customertype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customertype_id', to='customertype.Customertype', validators=[django.core.validators.MinValueValidator(1)])),
                ('enterby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customer_enter', to=settings.AUTH_USER_MODEL)),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='industry_id', to='industry.Industry')),
                ('modifyby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customer_modify', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
                'db_table': 'customer',
                'permissions': (('view_customer', 'Can view customer'),),
            },
        ),
    ]
