# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-26 05:24
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chartofaccount', '0004_auto_20170126_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debitcreditmemosubtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=250)),
                ('group', models.CharField(choices=[('D', 'Debit'), ('C', 'Credit')], max_length=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('applicationstatus', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('particular', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('C', 'Cancelled'), ('O', 'Posted'), ('P', 'Printed')], default='A', max_length=1)),
                ('enterdate', models.DateTimeField(auto_now_add=True)),
                ('modifydate', models.DateTimeField(default=datetime.datetime(2017, 1, 26, 13, 24, 39, 940000))),
                ('isdeleted', models.IntegerField(default=0)),
                ('credit1chartofaccount', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='credit1chartofaccount_id', to='chartofaccount.Chartofaccount', validators=[django.core.validators.MinValueValidator(1)])),
                ('credit2chartofaccount', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='credit2chartofaccount', to='chartofaccount.Chartofaccount', validators=[django.core.validators.MinValueValidator(1)])),
                ('debit1chartofaccount', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='debit1chartofaccount_id', to='chartofaccount.Chartofaccount', validators=[django.core.validators.MinValueValidator(1)])),
                ('debit2chartofaccount', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='debit2chartofaccount_id', to='chartofaccount.Chartofaccount', validators=[django.core.validators.MinValueValidator(1)])),
                ('enterby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='debitcreditmemosubtype_enter', to=settings.AUTH_USER_MODEL)),
                ('modifyby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='debitcreditmemosubtype_modify', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
                'db_table': 'debitcreditmemosubtype',
                'permissions': (('view_debitcreditmemosubtype', 'Can view debitcreditmemosubtype'),),
            },
        ),
    ]
