# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-30 06:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0003_auto_20170126_1105'),
        ('unit', '0003_auto_20170126_0802'),
    ]

    operations = [
    ]
