# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-24 02:06
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chartofaccount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wtax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=250)),
                ('rate', models.IntegerField(default=0)),
                ('wtaxtype_id', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('A', 'Active'), ('C', 'Cancelled'), ('O', 'Posted'), ('P', 'Printed')], default='A', max_length=1)),
                ('enterdate', models.DateTimeField(auto_now_add=True)),
                ('modifydate', models.DateTimeField(default=datetime.datetime(2017, 1, 24, 10, 6, 25, 464576))),
                ('isdeleted', models.IntegerField(default=0)),
                ('chartofaccount', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='wtaxchartofaccount_id', to='chartofaccount.Chartofaccount', validators=[django.core.validators.MinValueValidator(1)])),
                ('enterby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wtax_enter', to=settings.AUTH_USER_MODEL)),
                ('modifyby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wtax_modify', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
                'db_table': 'wtax',
                'permissions': (('view_wtax', 'Can view wtax'),),
            },
        ),
    ]
