# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-25 08:17
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Companyparameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('telno1', models.CharField(max_length=20)),
                ('telno2', models.CharField(blank=True, max_length=20, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=10, null=True)),
                ('contactperson_acctg1', models.CharField(max_length=75)),
                ('contactperson_acctg2', models.CharField(blank=True, max_length=75, null=True)),
                ('contactperson_it1', models.CharField(max_length=75)),
                ('contactperson_it2', models.CharField(blank=True, max_length=75, null=True)),
                ('contactperson_other1', models.CharField(blank=True, max_length=75, null=True)),
                ('contactperson_other2', models.CharField(blank=True, max_length=75, null=True)),
                ('sssnum', models.CharField(blank=True, max_length=20, null=True)),
                ('tinnum', models.CharField(blank=True, max_length=20, null=True)),
                ('rescertnum', models.CharField(blank=True, max_length=20, null=True)),
                ('issued_at', models.CharField(blank=True, max_length=20, null=True)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('wtaxsign_name', models.CharField(blank=True, max_length=50, null=True)),
                ('wtaxsign_tin', models.CharField(blank=True, max_length=20, null=True)),
                ('wtaxsign_position', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('C', 'Cancelled'), ('O', 'Posted'), ('P', 'Printed')], default='A', max_length=1)),
                ('enterdate', models.DateTimeField(auto_now_add=True)),
                ('modifydate', models.DateTimeField(default=datetime.datetime(2017, 1, 25, 16, 17, 52, 697000))),
                ('isdeleted', models.IntegerField(default=0)),
                ('enterby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='companyparameter_enter', to=settings.AUTH_USER_MODEL)),
                ('modifyby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='companyparameter_modify', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
                'db_table': 'companyparameter',
                'permissions': (('view_companyparameter', 'Can view companyparameter'),),
            },
        ),
    ]
