# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-30 06:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyparameter', '0003_auto_20170126_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyparameter',
            name='modifydate',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 30, 14, 51, 48, 685000)),
        ),
    ]
