# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-27 03:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccount', '0004_auto_20170126_1324'),
        ('chartofaccount', '0004_auto_20170126_1105'),
    ]

    operations = [
    ]
