# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-26 01:26
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chartofaccount', '0003_auto_20170126_0926'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productgroup', '0003_auto_20170126_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('departmentname', models.CharField(max_length=250)),
                ('sectionname', models.CharField(max_length=250)),
                ('groupname', models.CharField(max_length=250)),
                ('branchstatus', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1)),
                ('enterdate', models.DateTimeField(auto_now_add=True)),
                ('modifydate', models.DateTimeField(default=datetime.datetime(2017, 1, 26, 9, 26, 38, 134000))),
                ('isdeleted', models.IntegerField(default=0)),
                ('enterby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='department_enter', to=settings.AUTH_USER_MODEL)),
                ('expchartofaccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chartofaccount_department', to='chartofaccount.Chartofaccount')),
                ('modifyby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='department_modify', to=settings.AUTH_USER_MODEL)),
                ('productgroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productgroup_id', to='productgroup.Productgroup', validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'ordering': ['-pk'],
                'db_table': 'department',
                'permissions': (('view_department', 'Can view department'),),
            },
        ),
    ]
