# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-26 03:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_auto_20170126_0940'),
        ('department', '0002_auto_20170126_1105'),
    ]

    operations = [
    ]
