# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-26 00:02
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ataxcode', '0003_auto_20170126_0802'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vat', '0003_auto_20170126_0802'),
        ('inputvat', '0003_auto_20170126_0802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('address1', models.CharField(max_length=250)),
                ('address2', models.CharField(blank=True, max_length=250, null=True)),
                ('address3', models.CharField(blank=True, max_length=250, null=True)),
                ('tin', models.CharField(max_length=15)),
                ('telno', models.CharField(blank=True, max_length=20, null=True)),
                ('faxno', models.CharField(blank=True, max_length=20, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=10, null=True)),
                ('inputvatrate', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('multiplestatus', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('C', 'Cancelled'), ('O', 'Posted'), ('P', 'Printed')], default='A', max_length=1)),
                ('enterdate', models.DateTimeField(auto_now_add=True)),
                ('modifydate', models.DateTimeField(default=datetime.datetime(2017, 1, 26, 8, 2, 1, 630000))),
                ('isdeleted', models.IntegerField(default=0)),
                ('ataxcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ataxcode_id', to='ataxcode.Ataxcode', validators=[django.core.validators.MinValueValidator(1)])),
                ('enterby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_enter', to=settings.AUTH_USER_MODEL)),
                ('inputvat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputvat_id', to='inputvat.Inputvat', validators=[django.core.validators.MinValueValidator(1)])),
                ('modifyby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_modify', to=settings.AUTH_USER_MODEL)),
                ('vat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vat_id', to='vat.Vat', validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'ordering': ['-pk'],
                'db_table': 'supplier',
                'permissions': (('view_supplier', 'Can view supplier'),),
            },
        ),
    ]
