# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-26 03:05
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chartofaccount', '0004_auto_20170126_1105'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('unit', '0003_auto_20170126_1105'),
        ('department', '0002_auto_20170126_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departmentbudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(2100), django.core.validators.MinValueValidator(1980)])),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('formula', models.CharField(blank=True, max_length=255, null=True)),
                ('method', models.CharField(blank=True, max_length=255, null=True)),
                ('mjan', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('mfeb', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('mmar', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('mapr', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('mmay', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('mjun', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('mjul', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('maug', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('msep', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('moct', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('mnov', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('mdec', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('C', 'Cancelled'), ('O', 'Posted'), ('P', 'Printed')], default='A', max_length=1)),
                ('enterdate', models.DateTimeField(auto_now_add=True)),
                ('modifydate', models.DateTimeField(default=datetime.datetime(2017, 1, 26, 11, 5, 45, 651000))),
                ('isdeleted', models.IntegerField(default=0)),
                ('chartofaccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chartofaccount_departmentbudget_id', to='chartofaccount.Chartofaccount')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_departmentbudget_id', to='department.Department')),
                ('enterby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='departmentbudget_enter', to=settings.AUTH_USER_MODEL)),
                ('modifyby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='departmentbudget_modify', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_departmentbudget_id', to='unit.Unit')),
            ],
            options={
                'ordering': ['-pk'],
                'db_table': 'departmentbudget',
                'permissions': (('view_departmentbudget', 'Can view departmentbudget'),),
            },
        ),
        migrations.AlterUniqueTogether(
            name='departmentbudget',
            unique_together=set([('year', 'department', 'unit', 'chartofaccount')]),
        ),
    ]
